### ISSUE TITLE
Did you finetune DPR on the QAMPARI dataset?

### ISSUE THREAD

**Issue by drothermel** [samsam3232/qampari#1]
Thanks for the thorough READMEs! 

In the main readme you list results trained on QAMPARI and QAMPARI+NQ but in the model training section you don't mention doing any additional finetuning of the DPR model so I want to verify: Did you use a DPR model trained only on natural questions or did you finetune on QAMPARI?

**Comment by samsam3232** [comment]
Hey @drothermel,

Thank you for your feedback. We used a DPR model trained only on NQ as retriever in the reported results. We tried fine-tuning DPR on Qampari but we got a degradation in the performance. We leave fine-tuning DPR on QAMPARI for future works.

**Comment by drothermel** [comment]
Great, thanks for the additional details, good to know!
